### ISSUE TITLE
404 when you click "Software" then "Download"

### ISSUE THREAD

**Issue by pdurbin** [IQSS/docs.zeligproject.org#8]
If I go to http://docs.zeligproject.org/en/latest/ and click "Software" then "Download" I get a 404 at http://docs.zeligproject.org/en/latest/installation_quickstart.html#installing-r-and-zelig

**Comment by tercer** [comment]
Pages are back up now.  

IQSS/zeligproject.org#9 is again the issue here.  The Jenkins job is set up to call remote R scripts on the VM, but does not pay attention to whether those scripts fail.  Then Jenkins marks the job as a success and no one is notified.  

(It brings to mind the long standing, if not very pithy, conundrum:
"If Jenkins falls in a forest, and no one hears it, but the fall is noted in the middle of a thousand page log file, is Jenkins really set up correctly?")
